version: 2

project_name: musicon

before:
  hooks:
    - go mod download

builds:
  - id: musicon
    main: ./
    binary: musicon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath

archives:
  - id: musicon
    ids:
      - musicon
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else if eq .Arch \"386\" }}i386{{ else }}{{ .Arch }}{{ end }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

release:
  prerelease: auto
